---
title: ""
output: pdf_document
date: ""
---

### compare the effective number of tests (m_eff) according to each correction method. The 'n_prune' column gives the number of SNPs in the region after pruning all SNPs with r2 > 0.2. 

```{r setup, include=FALSE, echo=FALSE}
library(poolr)
library(dplyr)
library(readr)
library(gt)
library(knitr)
library(kableExtra)

#--------- compare Meff ----------------
meff_table <- function(df, prune_list, LD_matrix,caption){
  meff_table <- df %>% group_by(region) %>% 
    summarise(
      n           = length(snp),
      n_prune     = sum(snp %in% prune_list),
      Nyholt_2004 = meff(method = "nyholt", R = LD_matrix[unname(snp), unname(snp)]),
      Li_Ji_2005  = meff(method = "liji",   R = LD_matrix[unname(snp), unname(snp)]),
      Gao_2008    = meff(method = "gao",    R = LD_matrix[unname(snp), unname(snp)]),
      Galwey_2009 = meff(method = "galwey", R = LD_matrix[unname(snp), unname(snp)])
    )

  output <- kable(meff_table, caption=caption, format="latex", booktabs=TRUE) %>%
    kable_styling(latex_options= c("striped","hold_position"), full_width=TRUE)
  return(output)
}

load("mat.Rdata")
load("p_origin.Rdata")
load("m_LD1.Rdata")
load("p_LD1.Rdata")
m_keep <- read_table("maternal.in", col_names = FALSE)[[1]]
p_keep <- read_table("p_origin.in", col_names=FALSE)[[1]]
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
haplin_results <- read_table("../../NewAnalyses/New_Cleft_Haplin_Analysis/Input_and_Output_Files/maternal_folate_OFC_haplin.txt")
haplin_results <- merge(mat, haplin_results[,c("snp", "maternal_effectRR", "gxe_folate_mat", "maf", "no_env_mat_RR", "env_mat_RR")], by="snp")
names(haplin_results)[names(haplin_results) == 'gxe_folate_mat'] <- 'pval'
meff_table(haplin_results, m_keep, m_LD1 , "Maternal SNPs")
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
haplin_results <- read_table("../../NewAnalyses/New_Cleft_Haplin_Analysis/Input_and_Output_Files/parental_smoke_OFC_haplin.txt")
haplin_results <- merge(p_origin, haplin_results[,c("snp", "gxe_smoke_poo", "maf", "POO_effect_RR", "env_poo_RR", "no_env_poo_RR", "father_POO_effectRR")], by="snp")
names(haplin_results)[names(haplin_results) == 'gxe_smoke_poo'] <- 'pval'
meff_table(haplin_results, p_keep, p_LD1, "Parent origin SNPs")
```

